package gfx;

import java.awt.Color;

public class Colors
{
	public static final Color aliceBlue = new Color(0xf0f8ff);
	public static final Color antiqueWhite = new Color(0xfaebd7);
	public static final Color antiqueWhite1 = new Color(0xffefdb);
	public static final Color antiqueWhite2 = new Color(0xeedfcc);
	public static final Color antiqueWhite3 = new Color(0xcdc0b0);
	public static final Color antiqueWhite4 = new Color(0x8b8378);
	public static final Color aquamarine1 = new Color(0x7fffd4);
	public static final Color aquamarine2 = new Color(0x76eec6);
	public static final Color aquamarine3 = new Color(0x458b74);
	public static final Color azure1 = new Color(0xf0ffff);
	public static final Color azure2 = new Color(0xe0eeee);
	public static final Color azure3 = new Color(0xc1cdcd);
	public static final Color azure4 = new Color(0x838b8b);
	public static final Color beige = new Color(0xf5f5dc);
	public static final Color bisque1 = new Color(0xffe4c4);
	public static final Color bisque2 = new Color(0xeed5b7);
	public static final Color bisque3 = new Color(0xcdb79e);
	public static final Color bisque4 = new Color(0x8b7d6b);
	public static final Color black = new Color(0x000000);
	public static final Color blanchedAlmond = new Color(0xffebcd);
	public static final Color blue1 = new Color(0x0000ff);
	public static final Color blue2 = new Color(0x0000ee);
	public static final Color blue3 = new Color(0x00008b);
	public static final Color blueViolet = new Color(0x8a2be2);
	public static final Color brown = new Color(0xa52a2a);
	public static final Color brown1 = new Color(0xff4040);
	public static final Color brown2 = new Color(0xee3b3b);
	public static final Color brown3 = new Color(0xcd3333);
	public static final Color brown4 = new Color(0x8b2323);
	public static final Color burlywood = new Color(0xdeb887);
	public static final Color burlywood1 = new Color(0xffd39b);
	public static final Color burlywood2 = new Color(0xeec591);
	public static final Color burlywood3 = new Color(0xcdaa7d);
	public static final Color burlywood4 = new Color(0x8b7355);
	public static final Color cadetBlue = new Color(0x5f9ea0);
	public static final Color cadetBlue1 = new Color(0x98f5ff);
	public static final Color cadetBlue2 = new Color(0x8ee5ee);
	public static final Color cadetBlue3 = new Color(0x7ac5cd);
	public static final Color cadetBlue4 = new Color(0x53868b);
	public static final Color chartreuse1 = new Color(0x7fff00);
	public static final Color chartreuse2 = new Color(0x76ee00);
	public static final Color chartreuse3 = new Color(0x66cd00);
	public static final Color chartreuse4 = new Color(0x458b00);
	public static final Color chocolate = new Color(0xd2691e);
	public static final Color chocolate1 = new Color(0xff7f24);
	public static final Color chocolate2 = new Color(0xee7621);
	public static final Color chocolate3 = new Color(0xcd661d);
	public static final Color coral = new Color(0xff7f50);
	public static final Color coral1 = new Color(0xff7256);
	public static final Color coral2 = new Color(0xee6a50);
	public static final Color coral3 = new Color(0xcd5b45);
	public static final Color coral4 = new Color(0x8b3e2f);
	public static final Color cornflowerBlue = new Color(0x6495ed);
	public static final Color cornsilk1 = new Color(0xfff8dc);
	public static final Color cornsilk2 = new Color(0xeee8cd);
	public static final Color cornsilk3 = new Color(0xcdc8b1);
	public static final Color cornsilk4 = new Color(0x8b8878);
	public static final Color cyan1 = new Color(0x00ffff);
	public static final Color cyan2 = new Color(0x00eeee);
	public static final Color cyan3 = new Color(0x00cdcd);
	public static final Color cyan4 = new Color(0x008b8b);
	public static final Color darkGoldenrod = new Color(0xb8860b);
	public static final Color darkGoldenrod1 = new Color(0xffb90f);
	public static final Color darkGoldenrod2 = new Color(0xeead0e);
	public static final Color darkGoldenrod3 = new Color(0xcd950c);
	public static final Color darkGoldenrod4 = new Color(0x8b6508);
	public static final Color darkGreen = new Color(0x006400);
	public static final Color darkKhaki = new Color(0xbdb76b);
	public static final Color darkOliveGreen = new Color(0x556b2f);
	public static final Color darkOliveGreen1 = new Color(0xcaff70);
	public static final Color darkOliveGreen2 = new Color(0xbcee68);
	public static final Color darkOliveGreen3 = new Color(0xa2cd5a);
	public static final Color darkOliveGreen4 = new Color(0x6e8b3d);
	public static final Color darkOrange = new Color(0xff8c00);
	public static final Color darkOrange1 = new Color(0xff7f00);
	public static final Color darkOrange2 = new Color(0xee7600);
	public static final Color darkOrange3 = new Color(0xcd6600);
	public static final Color darkOrange4 = new Color(0x8b4500);
	public static final Color darkOrchid = new Color(0x9932cc);
	public static final Color darkOrchid1 = new Color(0xbf3eff);
	public static final Color darkOrchid2 = new Color(0xb23aee);
	public static final Color darkOrchid3 = new Color(0x9a32cd);
	public static final Color darkOrchid4 = new Color(0x68228b);
	public static final Color darkSalmon = new Color(0xe9967a);
	public static final Color darkSeaGreen = new Color(0x8fbc8f);
	public static final Color darkSeaGreen1 = new Color(0xc1ffc1);
	public static final Color darkSeaGreen2 = new Color(0xb4eeb4);
	public static final Color darkSeaGreen3 = new Color(0x9bcd9b);
	public static final Color darkSeaGreen4 = new Color(0x698b69);
	public static final Color darkSlateBlue = new Color(0x483d8b);
	public static final Color darkSlateGray = new Color(0x2f4f4f);
	public static final Color darkSlateGray1 = new Color(0x97ffff);
	public static final Color darkSlateGray2 = new Color(0x8deeee);
	public static final Color darkSlateGray3 = new Color(0x79cdcd);
	public static final Color darkSlateGray4 = new Color(0x528b8b);
	public static final Color darkTurquoise = new Color(0x00ced1);
	public static final Color darkViolet = new Color(0x9400d3);
	public static final Color deepPink1 = new Color(0xff1493);
	public static final Color deepPink2 = new Color(0xee1289);
	public static final Color deepPink3 = new Color(0xcd1076);
	public static final Color deepPink4 = new Color(0x8b0a50);
	public static final Color deepSkyBlue1 = new Color(0x00bfff);
	public static final Color deepSkyBlue2 = new Color(0x00b2ee);
	public static final Color deepSkyBlue3 = new Color(0x009acd);
	public static final Color deepSkyBlue4 = new Color(0x00688b);
	public static final Color dimGray = new Color(0x696969);
	public static final Color dodgerBlue1 = new Color(0x1e90ff);
	public static final Color dodgerBlue2 = new Color(0x1c86ee);
	public static final Color dodgerBlue3 = new Color(0x1874cd);
	public static final Color dodgerBlue4 = new Color(0x104e8b);
	public static final Color firebrick = new Color(0xb22222);
	public static final Color firebrick1 = new Color(0xff3030);
	public static final Color firebrick2 = new Color(0xee2c2c);
	public static final Color firebrick3 = new Color(0xcd2626);
	public static final Color firebrick4 = new Color(0x8b1a1a);
	public static final Color floralWhite = new Color(0xfffaf0);
	public static final Color forestGreen = new Color(0x228b22);
	public static final Color gainsboro = new Color(0xdcdcdc);
	public static final Color ghostWhite = new Color(0xf8f8ff);
	public static final Color gold1 = new Color(0xffd700);
	public static final Color gold2 = new Color(0xeec900);
	public static final Color gold3 = new Color(0xcdad00);
	public static final Color gold4 = new Color(0x8b7500);
	public static final Color goldenrod = new Color(0xdaa520);
	public static final Color goldenrod1 = new Color(0xffc125);
	public static final Color goldenrod2 = new Color(0xeeb422);
	public static final Color goldenrod3 = new Color(0xcd9b1d);
	public static final Color goldenrod4 = new Color(0x8b6914);
	public static final Color gray = new Color(0xbebebe);
	public static final Color gray1 = new Color(0x030303);
	public static final Color gray10 = new Color(0x1a1a1a);
	public static final Color gray11 = new Color(0x1c1c1c);
	public static final Color gray12 = new Color(0x1f1f1f);
	public static final Color gray13 = new Color(0x212121);
	public static final Color gray14 = new Color(0x242424);
	public static final Color gray15 = new Color(0x262626);
	public static final Color gray16 = new Color(0x292929);
	public static final Color gray17 = new Color(0x2b2b2b);
	public static final Color gray18 = new Color(0x2e2e2e);
	public static final Color gray19 = new Color(0x303030);
	public static final Color gray2 = new Color(0x050505);
	public static final Color gray20 = new Color(0x333333);
	public static final Color gray21 = new Color(0x363636);
	public static final Color gray22 = new Color(0x383838);
	public static final Color gray23 = new Color(0x3b3b3b);
	public static final Color gray24 = new Color(0x3d3d3d);
	public static final Color gray25 = new Color(0x404040);
	public static final Color gray26 = new Color(0x424242);
	public static final Color gray27 = new Color(0x454545);
	public static final Color gray28 = new Color(0x474747);
	public static final Color gray29 = new Color(0x4a4a4a);
	public static final Color gray3 = new Color(0x080808);
	public static final Color gray30 = new Color(0x4d4d4d);
	public static final Color gray31 = new Color(0x4f4f4f);
	public static final Color gray32 = new Color(0x525252);
	public static final Color gray33 = new Color(0x545454);
	public static final Color gray34 = new Color(0x575757);
	public static final Color gray35 = new Color(0x595959);
	public static final Color gray36 = new Color(0x5c5c5c);
	public static final Color gray37 = new Color(0x5e5e5e);
	public static final Color gray38 = new Color(0x616161);
	public static final Color gray39 = new Color(0x636363);
	public static final Color gray4 = new Color(0x0a0a0a);
	public static final Color gray40 = new Color(0x666666);
	public static final Color gray41 = new Color(0x696969);
	public static final Color gray42 = new Color(0x6b6b6b);
	public static final Color gray43 = new Color(0x6e6e6e);
	public static final Color gray44 = new Color(0x707070);
	public static final Color gray45 = new Color(0x737373);
	public static final Color gray46 = new Color(0x757575);
	public static final Color gray47 = new Color(0x787878);
	public static final Color gray48 = new Color(0x7a7a7a);
	public static final Color gray49 = new Color(0x7d7d7d);
	public static final Color gray5 = new Color(0x0d0d0d);
	public static final Color gray50 = new Color(0x7f7f7f);
	public static final Color gray51 = new Color(0x828282);
	public static final Color gray52 = new Color(0x858585);
	public static final Color gray53 = new Color(0x878787);
	public static final Color gray54 = new Color(0x8a8a8a);
	public static final Color gray55 = new Color(0x8c8c8c);
	public static final Color gray56 = new Color(0x8f8f8f);
	public static final Color gray57 = new Color(0x919191);
	public static final Color gray58 = new Color(0x949494);
	public static final Color gray59 = new Color(0x969696);
	public static final Color gray6 = new Color(0x0f0f0f);
	public static final Color gray60 = new Color(0x999999);
	public static final Color gray61 = new Color(0x9c9c9c);
	public static final Color gray62 = new Color(0x9e9e9e);
	public static final Color gray63 = new Color(0xa1a1a1);
	public static final Color gray64 = new Color(0xa3a3a3);
	public static final Color gray65 = new Color(0xa6a6a6);
	public static final Color gray66 = new Color(0xa8a8a8);
	public static final Color gray67 = new Color(0xababab);
	public static final Color gray68 = new Color(0xadadad);
	public static final Color gray69 = new Color(0xb0b0b0);
	public static final Color gray7 = new Color(0x121212);
	public static final Color gray70 = new Color(0xb3b3b3);
	public static final Color gray71 = new Color(0xb5b5b5);
	public static final Color gray72 = new Color(0xb8b8b8);
	public static final Color gray73 = new Color(0xbababa);
	public static final Color gray74 = new Color(0xbdbdbd);
	public static final Color gray75 = new Color(0xbfbfbf);
	public static final Color gray76 = new Color(0xc2c2c2);
	public static final Color gray77 = new Color(0xc4c4c4);
	public static final Color gray78 = new Color(0xc7c7c7);
	public static final Color gray79 = new Color(0xc9c9c9);
	public static final Color gray8 = new Color(0x141414);
	public static final Color gray80 = new Color(0xcccccc);
	public static final Color gray81 = new Color(0xcfcfcf);
	public static final Color gray82 = new Color(0xd1d1d1);
	public static final Color gray83 = new Color(0xd4d4d4);
	public static final Color gray84 = new Color(0xd6d6d6);
	public static final Color gray85 = new Color(0xd9d9d9);
	public static final Color gray86 = new Color(0xdbdbdb);
	public static final Color gray87 = new Color(0xdedede);
	public static final Color gray88 = new Color(0xe0e0e0);
	public static final Color gray89 = new Color(0xe3e3e3);
	public static final Color gray9 = new Color(0x171717);
	public static final Color gray90 = new Color(0xe5e5e5);
	public static final Color gray91 = new Color(0xe8e8e8);
	public static final Color gray92 = new Color(0xebebeb);
	public static final Color gray93 = new Color(0xededed);
	public static final Color gray94 = new Color(0xf0f0f0);
	public static final Color gray95 = new Color(0xf2f2f2);
	public static final Color gray97 = new Color(0xf7f7f7);
	public static final Color gray98 = new Color(0xfafafa);
	public static final Color gray99 = new Color(0xfcfcfc);
	public static final Color green1 = new Color(0x00ff00);
	public static final Color green2 = new Color(0x00ee00);
	public static final Color green3 = new Color(0x00cd00);
	public static final Color green4 = new Color(0x008b00);
	public static final Color greenYellow = new Color(0xadff2f);
	public static final Color honeydew1 = new Color(0xf0fff0);
	public static final Color honeydew2 = new Color(0xe0eee0);
	public static final Color honeydew3 = new Color(0xc1cdc1);
	public static final Color honeydew4 = new Color(0x838b83);
	public static final Color hotPink = new Color(0xff69b4);
	public static final Color hotPink1 = new Color(0xff6eb4);
	public static final Color hotPink2 = new Color(0xee6aa7);
	public static final Color hotPink3 = new Color(0xcd6090);
	public static final Color hotPink4 = new Color(0x8b3a62);
	public static final Color indianRed = new Color(0xcd5c5c);
	public static final Color indianRed1 = new Color(0xff6a6a);
	public static final Color indianRed2 = new Color(0xee6363);
	public static final Color indianRed3 = new Color(0xcd5555);
	public static final Color indianRed4 = new Color(0x8b3a3a);
	public static final Color ivory1 = new Color(0xfffff0);
	public static final Color ivory2 = new Color(0xeeeee0);
	public static final Color ivory3 = new Color(0xcdcdc1);
	public static final Color ivory4 = new Color(0x8b8b83);
	public static final Color khaki = new Color(0xf0e68c);
	public static final Color khaki1 = new Color(0xfff68f);
	public static final Color khaki2 = new Color(0xeee685);
	public static final Color khaki3 = new Color(0xcdc673);
	public static final Color khaki4 = new Color(0x8b864e);
	public static final Color lavender = new Color(0xe6e6fa);
	public static final Color lavenderBlush1 = new Color(0xfff0f5);
	public static final Color lavenderBlush2 = new Color(0xeee0e5);
	public static final Color lavenderBlush3 = new Color(0xcdc1c5);
	public static final Color lavenderBlush4 = new Color(0x8b8386);
	public static final Color lawnGreen = new Color(0x7cfc00);
	public static final Color lemonChiffon1 = new Color(0xfffacd);
	public static final Color lemonChiffon2 = new Color(0xeee9bf);
	public static final Color lemonChiffon3 = new Color(0xcdc9a5);
	public static final Color lemonChiffon4 = new Color(0x8b8970);
	public static final Color light = new Color(0xeedd82);
	public static final Color lightBlue = new Color(0xadd8e6);
	public static final Color lightBlue1 = new Color(0xbfefff);
	public static final Color lightBlue2 = new Color(0xb2dfee);
	public static final Color lightBlue3 = new Color(0x9ac0cd);
	public static final Color lightBlue4 = new Color(0x68838b);
	public static final Color lightCoral = new Color(0xf08080);
	public static final Color lightCyan1 = new Color(0xe0ffff);
	public static final Color lightCyan2 = new Color(0xd1eeee);
	public static final Color lightCyan3 = new Color(0xb4cdcd);
	public static final Color lightCyan4 = new Color(0x7a8b8b);
	public static final Color lightGoldenrod1 = new Color(0xffec8b);
	public static final Color lightGoldenrod2 = new Color(0xeedc82);
	public static final Color lightGoldenrod3 = new Color(0xcdbe70);
	public static final Color lightGoldenrod4 = new Color(0x8b814c);
	public static final Color lightGoldenrodYellow = new Color(0xfafad2);
	public static final Color lightGray = new Color(0xd3d3d3);
	public static final Color lightPink = new Color(0xffb6c1);
	public static final Color lightPink1 = new Color(0xffaeb9);
	public static final Color lightPink2 = new Color(0xeea2ad);
	public static final Color lightPink3 = new Color(0xcd8c95);
	public static final Color lightPink4 = new Color(0x8b5f65);
	public static final Color lightSalmon1 = new Color(0xffa07a);
	public static final Color lightSalmon2 = new Color(0xee9572);
	public static final Color lightSalmon3 = new Color(0xcd8162);
	public static final Color lightSalmon4 = new Color(0x8b5742);
	public static final Color lightSeaGreen = new Color(0x20b2aa);
	public static final Color lightSkyBlue = new Color(0x87cefa);
	public static final Color lightSkyBlue1 = new Color(0xb0e2ff);
	public static final Color lightSkyBlue2 = new Color(0xa4d3ee);
	public static final Color lightSkyBlue3 = new Color(0x8db6cd);
	public static final Color lightSkyBlue4 = new Color(0x607b8b);
	public static final Color lightSlateBlue = new Color(0x8470ff);
	public static final Color lightSlateGray = new Color(0x778899);
	public static final Color lightSteelBlue = new Color(0xb0c4de);
	public static final Color lightSteelBlue1 = new Color(0xcae1ff);
	public static final Color lightSteelBlue2 = new Color(0xbcd2ee);
	public static final Color lightSteelBlue3 = new Color(0xa2b5cd);
	public static final Color lightSteelBlue4 = new Color(0x6e7b8b);
	public static final Color lightYellow1 = new Color(0xffffe0);
	public static final Color lightYellow2 = new Color(0xeeeed1);
	public static final Color lightYellow3 = new Color(0xcdcdb4);
	public static final Color lightYellow4 = new Color(0x8b8b7a);
	public static final Color limeGreen = new Color(0x32cd32);
	public static final Color linen = new Color(0xfaf0e6);
	public static final Color magenta = new Color(0xff00ff);
	public static final Color magenta2 = new Color(0xee00ee);
	public static final Color magenta3 = new Color(0xcd00cd);
	public static final Color magenta4 = new Color(0x8b008b);
	public static final Color maroon = new Color(0xb03060);
	public static final Color maroon1 = new Color(0xff34b3);
	public static final Color maroon2 = new Color(0xee30a7);
	public static final Color maroon3 = new Color(0xcd2990);
	public static final Color maroon4 = new Color(0x8b1c62);
	public static final Color medium = new Color(0x66cdaa);
	public static final Color mediumAquamarine = new Color(0x66cdaa);
	public static final Color mediumBlue = new Color(0x0000cd);
	public static final Color mediumOrchid = new Color(0xba55d3);
	public static final Color mediumOrchid1 = new Color(0xe066ff);
	public static final Color mediumOrchid2 = new Color(0xd15fee);
	public static final Color mediumOrchid3 = new Color(0xb452cd);
	public static final Color mediumOrchid4 = new Color(0x7a378b);
	public static final Color mediumPurple = new Color(0x9370db);
	public static final Color mediumPurple1 = new Color(0xab82ff);
	public static final Color mediumPurple2 = new Color(0x9f79ee);
	public static final Color mediumPurple3 = new Color(0x8968cd);
	public static final Color mediumPurple4 = new Color(0x5d478b);
	public static final Color mediumSeaGreen = new Color(0x3cb371);
	public static final Color mediumSlateBlue = new Color(0x7b68ee);
	public static final Color mediumSpringGreen = new Color(0x00fa9a);
	public static final Color mediumTurquoise = new Color(0x48d1cc);
	public static final Color mediumVioletRed = new Color(0xc71585);
	public static final Color midnightBlue = new Color(0x191970);
	public static final Color mintCream = new Color(0xf5fffa);
	public static final Color mistyRose1 = new Color(0xffe4e1);
	public static final Color mistyRose2 = new Color(0xeed5d2);
	public static final Color mistyRose3 = new Color(0xcdb7b5);
	public static final Color mistyRose4 = new Color(0x8b7d7b);
	public static final Color moccasin = new Color(0xffe4b5);
	public static final Color navajoWhite1 = new Color(0xffdead);
	public static final Color navajoWhite2 = new Color(0xeecfa1);
	public static final Color navajoWhite3 = new Color(0xcdb38b);
	public static final Color navajoWhite4 = new Color(0x8b795e);
	public static final Color navyBlue = new Color(0x000080);
	public static final Color oldLace = new Color(0xfdf5e6);
	public static final Color oliveDrab = new Color(0x6b8e23);
	public static final Color oliveDrab1 = new Color(0xc0ff3e);
	public static final Color oliveDrab2 = new Color(0xb3ee3a);
	public static final Color oliveDrab4 = new Color(0x698b22);
	public static final Color orange1 = new Color(0xffa500);
	public static final Color orange2 = new Color(0xee9a00);
	public static final Color orange3 = new Color(0xcd8500);
	public static final Color orange4 = new Color(0x8b5a00);
	public static final Color orangeRed1 = new Color(0xff4500);
	public static final Color orangeRed2 = new Color(0xee4000);
	public static final Color orangeRed3 = new Color(0xcd3700);
	public static final Color orangeRed4 = new Color(0x8b2500);
	public static final Color orchid = new Color(0xda70d6);
	public static final Color orchid1 = new Color(0xff83fa);
	public static final Color orchid2 = new Color(0xee7ae9);
	public static final Color orchid3 = new Color(0xcd69c9);
	public static final Color orchid4 = new Color(0x8b4789);
	public static final Color pale = new Color(0xdb7093);
	public static final Color paleGoldenrod = new Color(0xeee8aa);
	public static final Color paleGreen = new Color(0x98fb98);
	public static final Color paleGreen1 = new Color(0x9aff9a);
	public static final Color paleGreen2 = new Color(0x90ee90);
	public static final Color paleGreen3 = new Color(0x7ccd7c);
	public static final Color paleGreen4 = new Color(0x548b54);
	public static final Color paleTurquoise = new Color(0xafeeee);
	public static final Color paleTurquoise1 = new Color(0xbbffff);
	public static final Color paleTurquoise2 = new Color(0xaeeeee);
	public static final Color paleTurquoise3 = new Color(0x96cdcd);
	public static final Color paleTurquoise4 = new Color(0x668b8b);
	public static final Color paleVioletRed = new Color(0xdb7093);
	public static final Color paleVioletRed1 = new Color(0xff82ab);
	public static final Color paleVioletRed2 = new Color(0xee799f);
	public static final Color paleVioletRed3 = new Color(0xcd6889);
	public static final Color paleVioletRed4 = new Color(0x8b475d);
	public static final Color papayaWhip = new Color(0xffefd5);
	public static final Color peachPuff1 = new Color(0xffdab9);
	public static final Color peachPuff2 = new Color(0xeecbad);
	public static final Color peachPuff3 = new Color(0xcdaf95);
	public static final Color peachPuff4 = new Color(0x8b7765);
	public static final Color pink = new Color(0xffc0cb);
	public static final Color pink1 = new Color(0xffb5c5);
	public static final Color pink2 = new Color(0xeea9b8);
	public static final Color pink3 = new Color(0xcd919e);
	public static final Color pink4 = new Color(0x8b636c);
	public static final Color plum = new Color(0xdda0dd);
	public static final Color plum1 = new Color(0xffbbff);
	public static final Color plum2 = new Color(0xeeaeee);
	public static final Color plum3 = new Color(0xcd96cd);
	public static final Color plum4 = new Color(0x8b668b);
	public static final Color powderBlue = new Color(0xb0e0e6);
	public static final Color purple = new Color(0xa020f0);
	public static final Color rebeccapurple = new Color(0x663399);
	public static final Color purple1 = new Color(0x9b30ff);
	public static final Color purple2 = new Color(0x912cee);
	public static final Color purple3 = new Color(0x7d26cd);
	public static final Color purple4 = new Color(0x551a8b);
	public static final Color red1 = new Color(0xff0000);
	public static final Color red2 = new Color(0xee0000);
	public static final Color red3 = new Color(0xcd0000);
	public static final Color red4 = new Color(0x8b0000);
	public static final Color rosyBrown = new Color(0xbc8f8f);
	public static final Color rosyBrown1 = new Color(0xffc1c1);
	public static final Color rosyBrown2 = new Color(0xeeb4b4);
	public static final Color rosyBrown3 = new Color(0xcd9b9b);
	public static final Color rosyBrown4 = new Color(0x8b6969);
	public static final Color royalBlue = new Color(0x4169e1);
	public static final Color royalBlue1 = new Color(0x4876ff);
	public static final Color royalBlue2 = new Color(0x436eee);
	public static final Color royalBlue3 = new Color(0x3a5fcd);
	public static final Color royalBlue4 = new Color(0x27408b);
	public static final Color saddleBrown = new Color(0x8b4513);
	public static final Color salmon = new Color(0xfa8072);
	public static final Color salmon1 = new Color(0xff8c69);
	public static final Color salmon2 = new Color(0xee8262);
	public static final Color salmon3 = new Color(0xcd7054);
	public static final Color salmon4 = new Color(0x8b4c39);
	public static final Color sandyBrown = new Color(0xf4a460);
	public static final Color seaGreen1 = new Color(0x54ff9f);
	public static final Color seaGreen2 = new Color(0x4eee94);
	public static final Color seaGreen3 = new Color(0x43cd80);
	public static final Color seaGreen4 = new Color(0x2e8b57);
	public static final Color seashell1 = new Color(0xfff5ee);
	public static final Color seashell2 = new Color(0xeee5de);
	public static final Color seashell3 = new Color(0xcdc5bf);
	public static final Color seashell4 = new Color(0x8b8682);
	public static final Color sienna = new Color(0xa0522d);
	public static final Color sienna1 = new Color(0xff8247);
	public static final Color sienna2 = new Color(0xee7942);
	public static final Color sienna3 = new Color(0xcd6839);
	public static final Color sienna4 = new Color(0x8b4726);
	public static final Color skyBlue = new Color(0x87ceeb);
	public static final Color skyBlue1 = new Color(0x87ceff);
	public static final Color skyBlue2 = new Color(0x7ec0ee);
	public static final Color skyBlue3 = new Color(0x6ca6cd);
	public static final Color skyBlue4 = new Color(0x4a708b);
	public static final Color slateBlue = new Color(0x6a5acd);
	public static final Color slateBlue1 = new Color(0x836fff);
	public static final Color slateBlue2 = new Color(0x7a67ee);
	public static final Color slateBlue3 = new Color(0x6959cd);
	public static final Color slateBlue4 = new Color(0x473c8b);
	public static final Color slateGray = new Color(0x708090);
	public static final Color slateGray1 = new Color(0xc6e2ff);
	public static final Color slateGray2 = new Color(0xb9d3ee);
	public static final Color slateGray3 = new Color(0x9fb6cd);
	public static final Color slateGray4 = new Color(0x6c7b8b);
	public static final Color snow1 = new Color(0xfffafa);
	public static final Color snow2 = new Color(0xeee9e9);
	public static final Color snow3 = new Color(0xcdc9c9);
	public static final Color snow4 = new Color(0x8b8989);
	public static final Color springGreen1 = new Color(0x00ff7f);
	public static final Color springGreen2 = new Color(0x00ee76);
	public static final Color springGreen3 = new Color(0x00cd66);
	public static final Color springGreen4 = new Color(0x008b45);
	public static final Color steelBlue = new Color(0x4682b4);
	public static final Color steelBlue1 = new Color(0x63b8ff);
	public static final Color steelBlue2 = new Color(0x5cacee);
	public static final Color steelBlue3 = new Color(0x4f94cd);
	public static final Color steelBlue4 = new Color(0x36648b);
	public static final Color tan = new Color(0xd2b48c);
	public static final Color tan1 = new Color(0xffa54f);
	public static final Color tan2 = new Color(0xee9a49);
	public static final Color tan3 = new Color(0xcd853f);
	public static final Color tan4 = new Color(0x8b5a2b);
	public static final Color thistle = new Color(0xd8bfd8);
	public static final Color thistle1 = new Color(0xffe1ff);
	public static final Color thistle2 = new Color(0xeed2ee);
	public static final Color thistle3 = new Color(0xcdb5cd);
	public static final Color thistle4 = new Color(0x8b7b8b);
	public static final Color tomato1 = new Color(0xff6347);
	public static final Color tomato2 = new Color(0xee5c42);
	public static final Color tomato3 = new Color(0xcd4f39);
	public static final Color tomato4 = new Color(0x8b3626);
	public static final Color turquoise = new Color(0x40e0d0);
	public static final Color turquoise1 = new Color(0x00f5ff);
	public static final Color turquoise2 = new Color(0x00e5ee);
	public static final Color turquoise3 = new Color(0x00c5cd);
	public static final Color turquoise4 = new Color(0x00868b);
	public static final Color violet = new Color(0xee82ee);
	public static final Color violetRed = new Color(0xd02090);
	public static final Color violetRed1 = new Color(0xff3e96);
	public static final Color violetRed2 = new Color(0xee3a8c);
	public static final Color violetRed3 = new Color(0xcd3278);
	public static final Color violetRed4 = new Color(0x8b2252);
	public static final Color wheat = new Color(0xf5deb3);
	public static final Color wheat1 = new Color(0xffe7ba);
	public static final Color wheat2 = new Color(0xeed8ae);
	public static final Color wheat3 = new Color(0xcdba96);
	public static final Color wheat4 = new Color(0x8b7e66);
	public static final Color white = new Color(0xffffff);
	public static final Color whiteSmoke = new Color(0xf5f5f5);
	public static final Color yellow1 = new Color(0xffff00);
	public static final Color yellow2 = new Color(0xeeee00);
	public static final Color yellow3 = new Color(0xcdcd00);
	public static final Color yellow4 = new Color(0x8b8b00);
	public static final Color yellowGreen = new Color(0x9acd32);

	public static int interpolate(float step, int... colors)
	{
		step = Math.max(Math.min(step, 1.0f), 0.0f);

		switch(colors.length)
		{
			case 0:
				throw new IllegalArgumentException("At least one color required.");

			case 1:
				return colors[0];

			case 2:
				return interpolateTwoColors(step, colors[0], colors[1]);

			default:
				int firstColorIndex = (int)(step * (colors.length - 1));
				if(firstColorIndex == (colors.length - 1))
				{
					return colors[colors.length - 1];
				}
				float stepAtFirstColorIndex = (float)firstColorIndex / (colors.length - 1);
				float localStep = (step - stepAtFirstColorIndex) * (colors.length - 1);
				return interpolateTwoColors(localStep, colors[firstColorIndex], colors[firstColorIndex + 1]);
		}

	}

	private static int interpolateTwoColors(float step, int color1, int color2)
	{
		step = Math.max(Math.min(step, 1.0f), 0.0f);
		int deltaAlpha = alpha(color2) - alpha(color1);
		int deltaRed = red(color2) - red(color1);
		int deltaGreen = green(color2) - green(color1);
		int deltaBlue = blue(color2) - blue(color1);

		int resultAlpha = (int)(alpha(color1) + (deltaAlpha * step));
		int resultRed = (int)(red(color1) + (deltaRed * step));
		int resultGreen = (int)(green(color1) + (deltaGreen * step));
		int resultBlue = (int)(blue(color1) + (deltaBlue * step));

		resultAlpha = Math.max(Math.min(resultAlpha, 255), 0);
		resultRed = Math.max(Math.min(resultRed, 255), 0);
		resultGreen = Math.max(Math.min(resultGreen, 255), 0);
		resultBlue = Math.max(Math.min(resultBlue, 255), 0);

		return (resultAlpha << 24) | (resultRed << 16) | (resultGreen << 8) | resultBlue;
	}

	private static int alpha(int color)
	{
		return (color >> 24) & 0xFF;
	}

	private static int red(int color)
	{
		return (color >> 16) & 0xFF;
	}

	private static int green(int color)
	{
		return (color >> 8) & 0xFF;
	}

	private static int blue(int color)
	{
		return color & 0xFF;
	}

	public static int interpolate(int rgb1, int rgb2, int length, int maxLength)
	{
		int Ar = (rgb1 >> 16) & 0xff;
		int Ag = (rgb1 >> 8) & 0xff;
		int Ab = rgb1 & 0xff;
		int Br = (rgb2 >> 16) & 0xff;
		int Bg = (rgb2 >> 8) & 0xff;
		int Bb = rgb2 & 0xff;
		int Yr = (int)(Ar + ((length * (Br - Ar)) / (float)maxLength));
		int Yg = (int)(Ag + ((length * (Bg - Ag)) / (float)maxLength));
		int Yb = (int)(Ab + ((length * (Bb - Ab)) / (float)maxLength));
		return 0xff000000 | ((Yr << 16) & 0xff0000) | ((Yg << 8) & 0xff00) | (Yb & 0xff);
	}

	public static int interpolate(Color color1, Color color2, int length, int maxLength)
	{
		return interpolate(color1.getRGB(), color2.getRGB(), length, maxLength);
	}
}
